name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us reproduce and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have tested with the latest version of the plugin
          required: true
        - label: I have tested with other plugins disabled to rule out conflicts
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead
      placeholder: Instead, this happened...
    validations:
      required: true

  - type: input
    id: plugin_version
    attributes:
      label: Plugin Version
      description: What version of Midnight Commander are you running?
      placeholder: "0.2.0"
    validations:
      required: true

  - type: input
    id: obsidian_version
    attributes:
      label: Obsidian Version
      description: What version of Obsidian are you using?
      placeholder: "1.4.16"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other (specify in additional context)
    validations:
      required: true

  - type: textarea
    id: console_logs
    attributes:
      label: Console Logs
      description: |
        Open Developer Tools (Ctrl+Shift+I) and check for errors in the Console tab.
        Include any relevant error messages or warnings.
      placeholder: Paste console output here...
      render: text

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here:
        - Screenshots or videos
        - Other plugins that might be relevant
        - Vault structure details
        - Any workarounds you've found
      placeholder: Any additional information...